version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "auto-merge"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
