name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio black flake8 mypy
    
    - name: Check formatting
      run: black --check swarm.py examples/ --extend-exclude="examples/__pycache__"
    
    - name: Lint with flake8
      run: flake8 swarm.py examples/ --max-line-length=100 --extend-ignore=E501
    
    - name: Type check with mypy
      run: mypy swarm.py --ignore-missing-imports
    
    - name: Test import
      run: python -c "import swarm; print('✓ Import successful')"
    
    - name: Run example (dry run)
      run: timeout 10 python swarm.py || true
